#!/usr/bin/env python3

import atexit
import tempfile
import os
import subprocess
import os.path
import math
import getopt
import sys
from time import sleep
from PIL import Image, ImageStat

FAKE_SENSOR = "/tmp/fake_light_sensor"
INPUT = "/dev/video0"
SLEEP_TIME = 10

# Magic to lux from image
def get_lightness(screenshot_cmd):
    f, path = tempfile.mkstemp()
    os.close(f)
    os.remove(path)

    path += ".jpg"
    subprocess.run([*screenshot_cmd, path], check=True)

    result = None
    with Image.open(path) as im:
        stat = ImageStat.Stat(im)
        r, g, b = stat.rms
        result = math.sqrt(0.241 * (r ** 2) + 0.691 * (g ** 2) + 0.068 * (b ** 2))

    os.remove(path)
    return result / 255


# Usage
def usage():
    print(
        "{} [--input=/dev/video0] [--output=/tmp/fake_light_sensor] [--sleep=10]".format(
            os.path.basename(__file__)
        )
    )


def exit(output):
    print("Shutdown fake sensor...")
    os.remove(output)


def main():
    # test params
    try:
        opts, args = getopt.getopt(
            sys.argv[1:],
            "i:o:s:hv",
            ["help", "input=", "output=", "sleep=", "verbose"],
        )
    except getopt.GetoptError as err:
        print(err)
        usage()
        sys.exit(2)

    # default values
    input = INPUT
    output = FAKE_SENSOR
    lux = 0
    sleep_time = SLEEP_TIME
    verbose = False

    # get params values
    for o, a in opts:
        if o in ("-v", "--verbose"):
            verbose = True
        elif o in ("-s", "--sleep"):
            sleep_time = int(a)
        elif o in ("-i", "--input"):
            input = a
        elif o in ("-o", "--output"):
            output = a
        elif o in ("-h", "--help"):
            usage()
            sys.exit()
        else:
            assert False, "unhandled option, see --help"

    if verbose:
        print("input: {}, output: {}".format(input, output))

    if os.path.isfile(output):
        print("{output} already running!".format(output))
        sys.exit(2)

    # main
    sensor = open(output, "w+")

    # on exit do
    atexit.register(exit, output)

    # main loop
    while True:
        # get sensor value
        try:
            lux = 100 * get_lightness(
                [
                    "ffmpeg",
                    "-hide_banner",
                    "-loglevel",
                    "panic",
                    "-i",
                    input,
                    "-vframes",
                    "1",
                ]
            )
        except FileNotFoundError as e:
            print("The binary ffmpeg is not found")
            sys.exit(1)
        except subprocess.CalledProcessError as e:
            print("Can't get lux, bad input device?")

        lux = int(lux)
        if verbose:
            print("lux={} | waiting {} seconds...".format(lux, sleep_time))

        # write sensor value
        sensor.seek(0)
        sensor.truncate()
        sensor.write(str(lux))
        sensor.flush()
        os.fsync(sensor)

        # wait
        sleep(sleep_time)


if __name__ == "__main__":
    main()
